# Generated by Django 5.0.2 on 2026-09-03 13:13

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=512, upload_to=documents.models.document_upload_path),
        ),
    ]
