# Generated by Django 5.0.2 on 2026-09-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_chunk_chunk_unique_chunk_index_per_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, choices=[('CONTRACT', 'Contract'), ('REGULATION', 'Regulation'), ('POLICY', 'Policy'), ('REPORT', 'Report'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='entities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
